// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.6.1
// source: broker.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MessageBroker_SendMessage_FullMethodName = "/broker.MessageBroker/SendMessage"
	MessageBroker_Subscribe_FullMethodName   = "/broker.MessageBroker/Subscribe"
)

// MessageBrokerClient is the client API for MessageBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC-service
type MessageBrokerClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MessageBroker_SubscribeClient, error)
}

type messageBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBrokerClient(cc grpc.ClientConnInterface) MessageBrokerClient {
	return &messageBrokerClient{cc}
}

func (c *messageBrokerClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, MessageBroker_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBrokerClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MessageBroker_SubscribeClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageBroker_ServiceDesc.Streams[0], MessageBroker_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &messageBrokerSubscribeClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MessageBroker_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type messageBrokerSubscribeClient struct {
	grpc.ClientStream
}

func (x *messageBrokerSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageBrokerServer is the server API for MessageBroker service.
// All implementations must embed UnimplementedMessageBrokerServer
// for forward compatibility
//
// gRPC-service
type MessageBrokerServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*empty.Empty, error)
	Subscribe(*SubscribeRequest, MessageBroker_SubscribeServer) error
	mustEmbedUnimplementedMessageBrokerServer()
}

// UnimplementedMessageBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedMessageBrokerServer struct {
}

func (UnimplementedMessageBrokerServer) SendMessage(context.Context, *SendMessageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageBrokerServer) Subscribe(*SubscribeRequest, MessageBroker_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedMessageBrokerServer) mustEmbedUnimplementedMessageBrokerServer() {}

// UnsafeMessageBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageBrokerServer will
// result in compilation errors.
type UnsafeMessageBrokerServer interface {
	mustEmbedUnimplementedMessageBrokerServer()
}

func RegisterMessageBrokerServer(s grpc.ServiceRegistrar, srv MessageBrokerServer) {
	s.RegisterService(&MessageBroker_ServiceDesc, srv)
}

func _MessageBroker_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBrokerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBroker_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBrokerServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBroker_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageBrokerServer).Subscribe(m, &messageBrokerSubscribeServer{ServerStream: stream})
}

type MessageBroker_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type messageBrokerSubscribeServer struct {
	grpc.ServerStream
}

func (x *messageBrokerSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

// MessageBroker_ServiceDesc is the grpc.ServiceDesc for MessageBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broker.MessageBroker",
	HandlerType: (*MessageBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MessageBroker_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _MessageBroker_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "broker.proto",
}
